<section class="account" id="account">
  <div class="account title">
    <h1>Mon compte</h1>
  </div>
  <?php
  if (flash()->hasSuccess('isConnected')) :
    echo flash()->getSuccess('isConnected');
  elseif (flash()->hasSuccess('modifyUser')) :
    echo flash()->getSuccess('modifyUser');
  elseif (flash()->hasSuccess('modifyPwd')) :
    echo flash()->getSuccess('modifyPwd');
  endif; ?>
  <div class="account section-content">
    <p>Vous êtes sur votre espace personnel, <?= htmlspecialchars($user->getFIrstName()); ?> <?= htmlspecialchars($user->getLastName()); ?>.</p>

    <p>Vous pouvez
      <a class="internal" href="<?= url('/modify') ?>">modifier vos informations
      </a> ou <a class="internal" href="<?= url('/updatePassword') ?>">
        modifier votre mot de passe.
      </a>.
    </p>
  </div>
</section>