<div class="account title">
  <h1>Mon compte</h1>
</div>
<div class="account section-content">
  <h2 class="center">
    Bienvenue <?= purify($user->getFIrstName()); ?> <?= purify($user->getLastName()); ?>
  </h2>
  <p class="center bold">
    Vous êtes sur votre espace personnel.
      <?php
      if (auth()->isAdmin()) : ?>
        <span>Vous êtes connecté en tant qu'administrateur.</span>
      <?php
      endif ?>
  </p>
    <?=
    form()->formGroup(
        'logoutButton',
        'group-row flex-center',
        'Informations utilisateurs',
        null,
        form()->onclick(
            'updateAccount-form',
            '/modify',
            'btn-update',
            'Modifier mes informations personnelles',
            false
        ) .
        form()->onclick(
            'updateAccount-form',
            '/updatePassword',
            'btn-update',
            'Modifier mon mot de passe',
            false
        )
    ); ?>
</div>
