<section class="login" id="login">
  <div class="login__title">
    <h1>Connexion</h1>
  </div>
  <div class="login__content">
    <div class="login__form">
      <form action="<?= url('/auth'); ?>" method="post">
        <div class="form-group">
          <label for="email">Email</label>
          <input type="email" name="email" id="email" class="form-control" placeholder="Email">
        </div>
        <div class="form-group">
          <label for="password">Mot de passe</label>
          <input type="password" name="password" id="password" class="form-control <?php if (flash()->hasError('password')) : ?>invalid <?php endif; ?>" placeholder="Mot de passe">
          <?php if (flash()->hasError('password')): ?>
          <div class="error">
            <?= flash()->getError('password') ?>
          </div>
          <?php endif; ?>
        </div>
        <button type="submit" class="btn btn-primary">Connexion</button>
      </form>
    </div>
    <div class="login__register">
      <p>Pas encore inscrit ? <a href="<?= url('/register'); ?>">Inscrivez-vous</a></p>
    </div>
  </div>

</section>