  <div class="popup-content">
    <div class="popup-header">
      <h1>Connexion</h1>
    </div>
    <div class="popup-body">
      <div role="form" class="login__form" aria-label="Formulaire de connexion">
          <?= form()->openForm(url('/auth'), 'POST') ?>
          <?= form()->formGroup(
              'login',
              'group-input',
              'Informations de connexion :',
              'identifiers',
              form()->input(
                  'email',
                  'addresse mail',
                  'email',
                  'email'
              ) .
              form()->input(
                  'password',
                  'Mot de passe',
                  'password',
                  'current-password'
              )
          ) ?>
          <?= form()->endFormWithSubmitCancel(
                  'loginSubmit',
                  null, 'Connexion', null, '/', 'Annuler') ?>
      </div>
      <div class="popup-footer" aria-labelledby="register">
        <p id="register" class="center">
          Pas encore inscrit ?
        </p>
          <?= form()->onclick('register-form', '/register', 'btn-no-style btn-register', "S'inscrire") ?>
      </div>
    </div>
  </div>
