<section class="login" id="login">
  <div class="login title">
    <h1>Connexion</h1>
  </div>
  <div class="login section-content">
    <div role="form" class="login__form" aria-label="Formulaire de connexion">
        <?= form()->open(url('/auth'), 'POST') ?>
        <?= form()->formGroup(
            null,
            'Informations de connexion',
            null,
            form()->input('email', 'Adresse mail', 'email', null, true, true) .
            form()->input('password', 'Mot de passe', 'password', null, true, true)
        ) ?>
        <?= form()->endFormWithSubmitCancel('btn btn-success', 'Connexion', '/', 'btn btn-cancel', 'Annuler') ?>
    </div>
    <div class="login__register" aria-labelledby="register">
      <p id="register">Pas encore inscrit ? <a href="<?= url('/register'); ?>">Inscrivez-vous</a></p>
    </div>
  </div>
</section>