  <div class="popup-content">
    <div class="popup-header">
      <h1>Modifiez vos informations</h1>
    </div>
    <div class="popup-body">
        <?= form()->openForm(url('/updateUser'), 'POST') ?>
        <?= form()->formGroup(
            'identity',
            'group-input',
            'identité',
            'identityLegend',
            form()->input(
                'society',
                'Société',
                'text',
                'organization',
                purify($user->getSociety()),
                false
            ) .
            form()->input(
                'firstname',
                'Prénom',
                'text',
                'given-name',
                purify($user->getFirstName())
            ) .
            form()->input(
                'lastname',
                'Nom',
                'text',
                'family-name',
                purify($user->getLastName())
            )
        ) ?>
        <?= form()->formGroup(
            'coordinates',
            'group-input',
            'Coordonnées',
            'coordinatesLegend',
            form()->input(
                'service',
                'Service',
                'text',
                null,
                purify($user->getService()),
                false
            ) .
            form()->input(
                'address',
                'addresse',
                'text',
                'address-line1',
                purify($user->getaddress())
            ) .
            form()->input(
                'complement',
                'Complément',
                'text',
                null,
                purify($user->getComplement()),
                false
            ) .
            form()->input(
                'zip',
                'Code postal',
                'text',
                'postal-code',
                purify($user->getZip())
            ) .
            form()->input(
                'city',
                'Ville',
                'text',
                null,
                $user->getCity()
            ) .
            form()->input('email', 'addresse mail', 'email', 'email', $user->getEmail())
        ) ?>
        <?= form()->endFormWithSubmitCancel(
                'modifyButtons',
                null,
                'Modifier',
                null, '/account', 'Annuler')
        ?>
    </div>
  </div>
