<section class="registrer" id="registrer">
    <div class="registrer title">
        <h1>Inscription</h1>
    </div>
    <div class="registrer_content">
        <form action="<?= url('/create'); ?>" method="post">
            <div class="form-group">
                <label for="society">Société</label>
                <input type="text" name="society" id="society" class="form-control" placeholder="Société">
            </div>
            <div class="form-group">
                <label for="lastname">Nom</label>
                <input required type="text" name="lastname" id="lastname" class="form-control" placeholder="Nom">
            </div>
            <div class="form-group">
                <label for="firstname">Prénom</label>
                <input required type="text" name="firstname" id="firstname" class="form-control" placeholder="Prénom">
            </div>
            <div class="form-group">
                <label for="service">Service</label>
                <input type="text" name="service" id="service" class="form-control" placeholder="Service">
            </div>
            <div class="form-group">
                <label for="adress">Adresse</label>
                <input required type="text" name="adress" id="adress" class="form-control" placeholder="Adresse">
            </div>
            <div class="form-group">
                <label for="complement">Complément</label>
                <input type="text" name="complement" id="complement" class="form-control" placeholder="Complément">
            </div>
            <div class="form-group">
                <label for="zip">Code postal</label>
                <input required type="text" name="zip" id="zip" class="form-control" placeholder="Code postal">
            </div>
            <div class="form-group">
                <label for="city">Ville</label>
                <input required type="text" name="city" id="city" class="form-control" placeholder="Ville">
            </div>
            <div class="form-group">
                <label for="email">Email</label>
                <input required type="email" name="email" id="email" class="form-control" placeholder="Email">
            </div>
            <div class="form-group">
                <label for="password">Mot de passe</label>
                <input required type="password" name="password" id="password" class="form-control" placeholder="Mot de passe">
            </div>
            <div class="form-group">
                <label for="passwordConfirm">Confirmation du mot de passe</label>
                <input required type="password" name="passwordConfirm" id="passwordConfirm" class="form-control" placeholder="Confirmation du mot de passe">
            </div>
            <button type="submit" class="btn btn-primary">Inscription</button>
        </form>
</section>