<section class="registrer" id="registrer">
  <div class="registrer title">
    <h1>Inscription</h1>
  </div>
  <div class="registrer_content">
    <?= form()->open(url('/create'), 'POST') ?>
      <?= form()->formGroup(null, 'group-input', 'Identité', null,
      form()->input('society', 'Société', 'text', null, false) .
      form()->input('firstname', 'Prénom', 'text', null, true) .
      form()->input('lastname', 'Nom', 'text', null, true)
      ) ?>
      <?= form()->formGroup(null, 'group-input', 'Coordonnées', 'coordinates',
        form()->input('service', 'Service', 'text', null, false) .
        form()->input('address', 'Adresse', 'text', null, true) .
        form()->input('complement', 'Complément', 'text', null, false) .
        form()->input('zip', 'Code postal', 'text', null, true) .
        form()->input('city', 'Ville', 'text', null, true)
        ) ?>
      <?= form()->formGroup(null, 'group-input', 'Informations de connexion', 'login',
        form()->input('email', 'Adresse mail', 'email', null, true) .
        form()->input('password', 'Mot de passe', 'password', null, true) .
        form()->input('password_confirm', 'Confirmation du mot de passe', 'password', null, true)
        ) ?>
      <?= form()->endFormWithAllButtons('btn btn-submit', "S'inscrire", 'cancel', '/login', 'btn btn-cancel', "Annuler", 'btn btn-reset', "Effacer") ?>
  </div>
</section>