<section class="UpdatePassword" id="UpdatePassword">
  <div class="UpdatePassword__title">
    <h1>Modifiez votre mot de passe</h1>
  </div>
  <?php var_dump($post); ?>
  <div class="UpdatePassword__content">
    <div class="updatePassword__form">
      <form action="<?= url('/updatePwd'); ?>" method="post">
        <div class="form-group">
          <label for="actualPassword">Mot de passe actuel</label>
          <input required type="password" name="actualPassword" id="actualPassword" class="form-control" placeholder="Mot de passe actuel">
          <?php if (flash()->hasError('actualPassword')) :
            echo flash()->getError('actualPassword');
          endif; ?>
        </div>
        <div class="form-group">
          <label for="newPassword">Nouveau mot de passe</label>
          <input required type="password" name="newPassword" id="newPassword" class="form-control" placeholder="Nouveau mot de passe">
          <?php if (flash()->hasError('newPassword')) :
            echo flash()->getError('newPassword');
          endif; ?>
        </div>
        <div class="form-group">
          <label for="passwordConfirm">Confirmation du mot de passe</label>
          <input required type="password" name="passwordConfirm" id="passwordConfirm" class="form-control" placeholder="Confirmation du mot de passe">
          <?php if (flash()->hasError('passwordConfirm')) :
            echo flash()->getError('passwordConfirm');
          endif; ?>
        </div>
        <button type="submit" class="btn btn-primary">Modifier</button>
      </form>
    </div>
  </div>
</section>