<section class="UpdatePassword" id="UpdatePassword">
  <div class="UpdatePassword title">
    <h1>Modifiez votre mot de passe</h1>
  </div>

  <div class="UpdatePassword section-content">
    <div class="updatePassword__form">
      <?= form()->open(url('/updatePwd'), 'POST') ?>
      <?= form()->formGroup(
              null,
              'Ancien mot de passe',
              null,
              form()->input('actualPassword', 'Mot de passe', 'password', null, true))
      ?>
      <?= form()->formGroup(
              null,
              null,
              null,
              form()->input('newPassword', 'Nouveau mot de passe', 'password', null, true) .
              form()->input('passwordConfirm', 'Confirmation du nouveau mot de passe', 'password', null, true)
      ) ?>
      <?= form()->endFormWithSubmitCancel('btn btn-submit', 'Modifier', '/account', 'btn btn-cancel', 'Annuler') ?>
    </div>
  </div>
</section>