  <div class="popup-content">
    <div class="popup-header">
      <h1>Modifiez votre mot de passe</h1>
    </div>
    <div class="popup-body">
      <div class="updatePassword__form">
          <?= form()->openForm(url('/updatePwd'), 'POST', 'modifyPasswordForm') ?>
          <?= form()->formGroup(
              'actualPass',
              'group-input',
              'Ancien mot de passe',
              'actualPassLegend',
              form()->input('actual_password', 'Mot de passe', 'password', 'current-password')
          )
          ?>
          <?= form()->formGroup(
              'newPass',
              'group-input',
              'Nouveau mot de passe',
              'newPassLegend',
              form()->input('new_password', 'Nouveau mot de passe', 'password') .
              form()->input('password_confirm', 'Confirmation du nouveau mot de passe', 'password')
          ) ?>
          <?= form()->endFormWithSubmitCancel(
                  'modifyPasswordButton',
                  null,
                  'Modifier',
                  null, '/account', 'Annuler') ?>
      </div>
    </div>
  </div>
