<nav role="navigation" class="footer-menu flex-row" id="footerMenu" aria-label="Réseaux sociaux et mentions légales">
    <div class="footer-menu__social flex-row" id="social">
        <ul class="footer-menu__social__list flex-row" id="socialList">
            <li class="footer-menu__link external list10">
                <a href="https://www.facebook.com/kiffportage" target=" _blank">
                    <img src="images/social/facebook.png" alt="Facebook" />
                </a>
            </li>
            <li class="footer-menu__link external" id="cv">
                <a href="https://f-nour.github.io/cv" target='_blank'>
                    <img src="images/components/cv.png" alt="Consulter mon CV">
                </a>
            </li>
            <li class="footer-menu__link external">
                <a href="https://www.linkedin.com/in/kiff-portage-b8a8b817b/" target=" _blank">
                    <img src="images/social/linkedin.png" alt="Linkedin" />
                </a>
            </li>
        </ul>
    </div>
    <div class="footer-menu__legal flex-row">
        <ul class="footer-menu__legal__list flex-row" id="menuLegal">
            <li data-menus class="footer-menu__link internal">
                <a href="/legal">Mentions légales</a>
            </li>
            <li data-menus class="footer-menu__link internal">
                <a href="/accessibility">Charte d'Accessibilité</a>
            </li>
            <li data-menus class="footer-menu__link internal">
                <a href="/plan">Plan du site</a>
            </li>
            <li>
                <span>&copy; 2022 Tous droits réservés </span>
            </li>
        </ul>
    </div>
</nav>