<!-- document HTML5 -->
<!DOCTYPE html>
<!-- Langue dans laquelle est écrite le site internet-->
<html lang="fr">
<!-- Début du head -->

<head>
    <!-- link -->
    <link rel="icon" type="image/x-icon" href="/public/images/logo/favicon.ico" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/reseter.css" /> <!-- reseter -->
    <link rel="stylesheet" href="/assets/css/style.css" />
    <!--script -->
    <script type="module" src="/assets/js/script.js" async></script>
    <!-- Titre de la page web -->
    <title><?= $title ?></title> <!-- titre généré dynamiquement par le serveur -->
    <!-- Balise meta pour les moteurs de recherche -->
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <meta name="author" content="Kiff ton Écharpe" />
    <meta name="robots" content="index,follow" />
    <meta name="revisit-after" content="1 days" />
    <!-- Balises de localisation -->
    <meta name="language" content="fr" />
    <meta name="geo.country" content="FR" />
    <meta name="geo.placename" content="Bordeaux" />
    <meta name="geo.position" content="44.833328;-0.56667" />
    <meta name="ICBM" content="44.833328;-0.56667" />
    <!-- Balise OpenGraph -->
    <meta property="og:title" content="" />
    <meta property="og:type" content="website" />
    <meta property="og:url' content=""  />
    <meta property=" og:image" content="" />
    <meta property="og:description" content="" />
    <meta property="og:site_name" content="" />
    <meta property="og:locale" content="fr_FR" />
    <!-- Balise Twitter -->
    <meta property="twitter:card" content="summary" />
    <!-- <meta property="twitter:site" content="@" /> -->
    <meta property="twitter:creator" content="@Noureddine_f" />
    <meta property="twitter:title" content="" />
    <meta property="twitter:description" content="" />
    <meta property="twitter:url' content=""  />
    <meta property=" twitter:image" content="" />
    <!-- Balise Dublin Core -->
    <meta name="DC.title" content="" />
    <meta name="DC.description" content="" />
    <meta name="DC.subject" content="Auto-entrepreneur en développement web et formation en protection de l'enfance/Violences conjugales" />
    <meta name="DC.publisher" content="Kiff ton Echarpe" />
    <meta name="DC.contributor" content="3W Academy" />
    <meta name="DC.date" content="08/08/2022" />
    <meta name="DC.type" content="website" />
    <meta name="DC.format" content="text/html" />
    <meta name="DC.identifier" content="" />
    <meta name="DC.language" content="fr" />
    <meta name="DC.coverage" content="World" />
    <meta name="DC.rights" content="Kiff Ton Echarpe" />
</head>