<section class="registrer">
  <div class="registrer__title">
    <h1>Inscription</h1>
  </div>
  <?php var_dump($_POST); ?>
  <div class="registrer__content">
    <div class="registrer__form">
      <?php if (isset($_GET['errors'])): ?>
        <div class="alert alert-danger">
            <?php foreach ($_GET['errors'] as $error): ?>
            <p><?= $error ?></p>
            <?php endforeach; ?>
        </div>
      <?php endif; ?>
      <form method="post" action="<?= url('/create') ?>">
        <div class="registrer__form input">
          <label for="society">Société</label>
          <input type="text" name="society" id="society" placeholder="Société" value="<?= $society ?? '' ?>">
          <div class="text-danger"><?= $errors['society'] ?? '' ?></div>
        </div>
        <div class="registrer__form input">
          <label for="lastname">Nom</label>
          <input type="text" name="lastname" id="lastname" placeholder="Nom" value="<?= $lastname ?? '' ?>">
          <div class="text-danger"><?= $errors['lastname'] ?? '' ?></div>
        </div>
        <div class="registrer__form input">
          <label for="firstname">Prénom</label>
          <input type="text" name="firstname" id="firstname" placeholder="Prénom" value="<?= $firstname ?? '' ?>">
          <div class="text-danger"><?= $errors['firstname'] ?? '' ?></div>
        </div>
        <div class="registrer__form input">
          <label for="service">service</label>
          <input type="text" name="service" id="service" placeholder="Service" value="<?= $service ?? '' ?>">
          <div class="text-danger"><?= $errors['service'] ?? '' ?></div>
        </div>
        <div class="'registrer__form input">
          <label for="adress">Adresse</label>
          <input type="text" name="adress" id="adress" placeholder="Adresse" value="<?= $adress ?? '' ?>">
        <div class="registrer__form input">
          <label for="complement">Complément d'adresse</label>
          <input type="text" name="complement" id="complement" placeholder="Complément d'adresse" value="<?= $complement ?? '' ?>">
          <div class="text-danger"><?= $errors['complement'] ?? '' ?></div>
        </div>
        <div class="registrer__form input">
          <label for="zip">Code postal</label>
          <input type="text" name="zip" id="zip" placeholder="Code postal" value="<?= $zip ?? '' ?>">
          <div class="text-danger"><?= $errors['zip'] ?? '' ?></div>
        </div>
        <div class="registrer__form input">
          <label for="city">Ville</label>
          <input type="text" name="city" id="city" placeholder="Ville" value="<?= $city ?? '' ?>">
          <div class="text-danger"><?= $errors['city'] ?? '' ?></div>
        </div>
        <div class="resigter__form input">
          <label for="email">Email</label>
          <input type="email" name="email" id="email" placeholder="Email" value="<?= $email ?? '' ?>">
          <div class="text-danger"><?= $errors['email'] ?? '' ?></div>
        </div>
        <div class="resigter__form input">
          <label for="password">Mot de passe</label>
          <input type="password" name="password" id="password" placeholder="Mot de passe" value="<?= $password ?? '' ?>">
          <div class="text-danger"><?= $errors['password'] ?? '' ?></div>
        </div>
        <div class="resigter__form input">
          <label for="password_confirm">Confirmation du mot de passe</label>
          <input type="password" name="password_confirm" id="password_confirm" placeholder="Confirmation du mot de passe" value="<?= $password_confirm ?? '' ?>">
          <div class="text-danger"><?= $errors['password_confirm'] ?? '' ?></div>
        </div>
        <div class="registrer_form button">
          <button type="submit" name="registrer">Inscription</button>
        </div>
      </form>
    </div>
  </div>
</section>
