<!-- Début du head -->
<head>
    <!-- link -->
    <link rel="icon" type="image/x-icon" href="/public/images/logo/favicon.ico" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/reseter.css" /> <!-- reseter -->
    <link rel="stylesheet" href="public/assets/css/style.css" />
    <!--script -->
    <script type="module" src="public/assets/js/script.js" async></script>
    <!-- Titre de la page web -->
    <title><?= $title ?></title> <!-- titre généré dynamiquement par le serveur -->
    <!-- Balise meta pour éviter le référencement sur les moteurs de recherche -->
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="revised" content="08/08/2022" />
    <meta name="robots" content="noindex">
    <meta name="robots" content="nofollow">
    <meta name="googlebot" content="noindex">
</head>