<h1>Le site internet a rencontré une erreure interne.</h1>

<p class="h2">Nous sommes le <?= date('d/m/Y') ?> à <?= date('h:i:s') ?>.</p>

<p class="h3">Merci de faire une capture d'écran de cette page et de <a class="internal" href="mailto:kiffportage@gmail.com">nous l'envoyer</a> pour nous aider à résoudre le problème.</p>

<p class="h3">Après avoir fait une capture d'écran, vous pouvez cliquer sur un lien du menu ou aller <a class="internal" href="<?= url('/') ?>">Retourner à l'accueil du site</a></p>