<!-- document HTML5 -->
<!DOCTYPE html>
<!-- Langue dans laquelle est écrite le site internet-->
<html lang="fr">
<?php require 'Templates/Components/admin_head.phtml'; ?>

<!-- Début du body -->

<body>
    <header class="header" id="header">
        <?php require 'Templates/Components/admin_nav.phtml'; ?>
    </header>
    <div class="container">
        <main class="main" id="main">
            <?php require $template ?>
        </main>
    </div>
</body>

</html>