<nav role="navigation" class="header-menu flex-row" id="headerMenu">
  <ul class=" header-menu__list flex-row" id="menuList">
    <li data-menus class="header-menu__link internal logo" id="logo">
      <a href="<?= url('/') ?>" title="Accueil" class="flex-row">
        Kiff Ton Écharpe
      </a>
    </li>
    <li data-menus class="header-menu__link internal list1">
      <a href=<?= url('/products') ?>" title=" Produits">Mes services</a>
    </li>
    <li data-menus class="header-menu__link internal list2">
      <a href="<?= url('/about') ?>" title="A propos">Mieux me connaître</a>
    </li>
    <li data-menus class="header-menu__link internal list3">
      <a href="<?= url('/contact') ?>" title="Contact">Me contacter</a>
    </li>
    <?php if (auth()->isAuthenticated()): ?>
      <li data-menus class="header-menu__link internal list4">
        <a href="<?= url('/account') ?>" title="Mon compte">Mon compte</a>
      </li>
      <li data-menus class="header-menu__link internal list5">
        <a href="<?= url('/logout') ?>" title="Déconnexion">Déconnexion</a>
      </li>
    <?php else : ?>
    <li data-menus class="header-menu__link internal">
      <a href="<?= url('/login') ?>" title="Connexion">Connexion</a>
    </li>
    <?php endif; ?>
  </ul>
</nav>