<!DOCTYPE html>
<!-- Langue dans laquelle est écrite le site internet-->
<html lang="fr">

<?php
require 'Templates/Partials/_head.phtml'; ?>

<!-- Début du body -->

<body>
<header class="header" id="header">
    <?php
    require 'Templates/Partials/_nav.phtml';
    ?>
</header>
<div class="container">
  <main class="main" id="main">
      <?php
      if ($alert) : ?>
        <section role="alert">
            <?= $alert; ?>
        </section>
      <?php
      endif ?>
    <section id="<?= $view ?>" class="<?= $view ?>" name="<?= $name ?>" role="main">
        <?php
        require $template;
        ?>
    </section>
  </main>
  <footer class="footer" id="footer" role="contentinfo">
      <?php
      require 'Templates/Partials/_footer.phtml'; ?>
  </footer>
</div>
</body>

</html>