<!DOCTYPE html>
<!-- Langue dans laquelle est écrite le site internet-->
<html lang="fr">
<?php
require 'Templates/Components/_head.phtml'; ?>

<!-- Début du body -->

<body>
<header class="header" id="header">
  <?php
  require 'Templates/Components/_nav.phtml'; ?>
</header>
<div class="container">

  <main class="main" id="main">
    <?php require $template ?>
  </main>
  <footer class=" footer" id="footer">
    <?php
    require 'Templates/Components/_footer.phtml'; ?>
  </footer>
</div>
</body>

</html>