<nav role="navigation" class="footer-menu flex-row" id="footerMenu" aria-label="Réseaux sociaux et mentions légales">
    <ul class="footer-menu__list flex-row" id="socialList">
        <li class="footer-menu__link external list10">
            <a href="https://www.facebook.com/kiffportage" target=" _blank">
                <img src="public/images/social/facebook.png" alt="Facebook" />
            </a>
        </li>
        <li class="footer-menu__link external" id="cv">
            <a href="https://f-nour.github.io/cv" target='_blank'>
                <img src="public/images/components/cv.png" alt="Consulter mon CV">
            </a>
        </li>
        <li class="footer-menu__link external">
            <a href="https://www.linkedin.com/in/kiff-portage-b8a8b817b/" target=" _blank') ?>">
                <img src="public/images/social/linkedin.png" alt="Linkedin" />
            </a>
        </li>
    </ul>
    <ul class="footer-menu__list flex-row" id="menuLegal">
        <li data-menus class="footer-menu__link internal">
            <a href="<?= url('/legal') ?>">Mentions légales</a>
        </li>
        <li data-menus class="footer-menu__link internal">
            <a href="<?= url('/accessibility') ?>">Charte d'Accessibilité</a>
        </li>
        <li data-menus class="footer-menu__link internal">
            <a href="<?= url('/plan') ?>">Plan du site</a>
        </li>
    </ul>
    <div class="footer-menu__copyright">
        <span>&copy; 2022 Kiff Ton Écharpe : Tous droits réservés </span>
    </div>
</nav>