<div class="about title" id="aboutTitle" name="aboutTitle">
  <h1>À propos de nous</h1>
</div>
<div class="about section-content" id="aboutContent">
  <div class="about-header">
    <div class="about-title">
      <h2><?= purify($about->status) . ' "' . purify($about->society) ?>"</h2>
    </div>
  </div>
  <p>
    La société <?= purify($about->society) ?> est située à <?= purify($about->city) ?>,
  </p>
  <p>
    Son adresse email est <a class="external" href="mailto:<?= purify($about->mail) ?>">
          <?= purify($about->mail) ?>
    </a>.
  </p>
</div>