<section class="about" id="about" name="about">
  <div class="about title" id="aboutTitle" name="aboutTitle">
    <h1>À propos de nous</h1>
  </div>
  <div class="about section-content" id="aboutContent" name="aboutContent">
    <h2><?= htmlspecialchars($about->status) . ' about.phtml' . htmlspecialchars($about->society) ?>"</h2>
    <p>
      La société <?= htmlspecialchars($about->society) ?> est située à <?= htmlspecialchars($about->city) ?>,
    </p>
    <p>
      son email est <a class="external" href="mailto:<?= htmlspecialchars($about->mail) ?>"><?= htmlspecialchars($about->mail) ?></a>,
    </p>
  </div>
</section>