<div class="admin title center">
  <h1>Espace Administrateur</h1>
</div>
<div class="admin content">
  <div>
    <h2 class="center">Bienvenue sur l'espace administrateur <?= purify($admin->getFIrstName()); ?> <?= purify($admin->getLastName()); ?></h2>
  </div>
  <div class="flex-center">
    <?= form()->onclick(
        'updateAbout-form',
        '/admin/editAbout',
        "btn-update",
        'Modifier les informations du site internet',
        false
    ); ?>
  </div>
</div>
